<details>
   <summary><b>Table of Contents</b></summary>

   - [1. Review Data](#1-review-data)
   - [2. Train - Test Split](#2-train---test-split)
   - [3. Model Selection](#3-model-selection)
   - [4. Test with Best Model](#4-test-with-best-model)
   - [5. Tuning Model](#5-tuning-model)
   - [6. Evaluate Model](#6-evaluate-model)
     - [6.1. Train - Test Split](#61-train---test-split)
     - [6.2. Cross Validation (K-Fold)](#62-cross-validation-k-fold)
     - [6.3. Visualization](#63-visualization)
   - [7. Save Model](#7-save-model)
</details>

In [1]:
import warnings
import pandas as pd

from sklearn.pipeline      import Pipeline
from sklearn.compose       import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

from sklearn.svm          import SVR
from sklearn.tree         import DecisionTreeRegressor
from sklearn.neighbors    import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.ensemble     import RandomForestRegressor, HistGradientBoostingRegressor
from xgboost              import XGBRegressor

from sklearn.model_selection import train_test_split
from sklearn.metrics         import root_mean_squared_error, mean_absolute_error, r2_score

warnings.filterwarnings('ignore', category=FutureWarning)
warnings.filterwarnings('ignore', category=UserWarning)

pd.set_option('display.float_format', lambda x: f'{x:.3e}')

## **1. Review Data**
---

In [2]:
df = pd.read_csv('../data/data_model.csv')
df.head()

,Company Name,Location,Headquarters,Size,Type of ownership,Industry,Sector,Revenue,job_simplified,seniority,Rating Category,job_state,Python_yn,Spark,AWS_yn,Average Salary
0,Tecolote Research,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),data scientist,Other,Medium Rating,NM,1,0,0,7.200e+04
1,University of Maryland Medical System,"Linthicum, MD","Baltimore, MD",10000+ employees,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),data scientist,Other,Medium Rating,MD,1,0,0,8.750e+04
2,KnowBe4,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,Company - Private,Security Services,Business Services,$100 to $500 million (USD),data scientist,Other,High Rating,FL,1,1,0,8.500e+04
3,PNNL,"Richland, WA","Richland, WA",1001 to 5000 employees,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),data scientist,Other,Medium Rating,WA,1,0,0,7.650e+04
4,Affinity Solutions,"New York, NY","New York, NY",51 to 200 employees,Company - Private,Advertising & Marketing,Business Services,Unknown,data scientist,Other,Low Rating,NY,1,0,0,1.145e+05

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 742 entries, 0 to 741
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Company Name       742 non-null    object
 1   Location           742 non-null    object
 2   Headquarters       742 non-null    object
 3   Size               742 non-null    object
 4   Type of ownership  742 non-null    object
 5   Industry           742 non-null    object
 6   Sector             742 non-null    object
 7   Revenue            742 non-null    object
 8   job_simplified     742 non-null    object
 9   seniority          742 non-null    object
 10  Rating Category    742 non-null    object
 11  job_state          742 non-null    object
 12  Python_yn          742 non-null    int64
 13  Spark              742 non-null    int64
 14  AWS_yn             742 non-null    int64
 15  Average Salary     742 non-null    float64
dtypes: float64(1), int64(3), object(12)
memory usage: 92.9+ KB

In [4]:
df.describe()

       Python_yn     Spark    AWS_yn  Average Salary
count  7.420e+02 7.420e+02 7.420e+02       7.420e+02
mean   5.283e-01 2.251e-01 2.372e-01       1.015e+05
std    4.995e-01 4.179e-01 4.257e-01       3.746e+04
min    0.000e+00 0.000e+00 0.000e+00       1.550e+04
25%    0.000e+00 0.000e+00 0.000e+00       7.350e+04
50%    1.000e+00 0.000e+00 0.000e+00       9.750e+04
75%    1.000e+00 0.000e+00 0.000e+00       1.225e+05
max    1.000e+00 1.000e+00 1.000e+00       2.540e+05

## **2. Train - Test Split**
---

In [5]:
X = df.drop('Average Salary', axis=1)
y = df['Average Salary']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"X_train shape: {X_train.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"X_test  shape: {X_test.shape}")
print(f"y_test  shape: {y_test.shape}")

X_train shape: (593, 15)
y_train shape: (593,)
X_test  shape: (149, 15)
y_test  shape: (149,)

## **3. Model Selection**
---

In [6]:
def create_regression_pipeline(model_name):
    regression_models = {
        'SVR'                      : SVR(),
        'XGBoost'                  : XGBRegressor(random_state=42),
        'KNeighbors'               : KNeighborsRegressor(),
        'DecisionTree'             : DecisionTreeRegressor(random_state=42),
        'RandomForest'             : RandomForestRegressor(random_state=42),
        'LinearRegression'         : LinearRegression(),
        'HistogramGradientBoosting': HistGradientBoostingRegressor(random_state=42),
    }

    categorical_features = X.select_dtypes(include=['object']).columns.tolist()
    numerical_features   = X.select_dtypes(include=['int64', 'float64']).columns.tolist()
    
    preprocessor = ColumnTransformer(
        transformers=[
            ('num', StandardScaler(), numerical_features),
            ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False), categorical_features)
        ]
    )

    regression_pipeline = Pipeline(
        steps=[
            ('preprocessor', preprocessor),
            ('regressor'   , regression_models[model_name])
        ]
    )

    pipeline_dict = {model_name: regression_pipeline}
    return pipeline_dict


def create_all_regression_pipelines():
    regression_model_names = ['RandomForest', 'SVR', 'LinearRegression', 'KNeighbors', 'DecisionTree', 'XGBoost', 'HistogramGradientBoosting']

    all_pipelines = {}
    for model_name in regression_model_names:
        pipeline_dict = create_regression_pipeline(model_name)
        all_pipelines.update(pipeline_dict)
        
    return all_pipelines


def train_evaluate_model_with_df(model_name, model, X_train, y_train, X_test, y_test, results_df):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    rmse = root_mean_squared_error(y_test, y_pred)
    mae  = mean_absolute_error(y_test, y_pred)
    r2   = r2_score(y_test, y_pred)

    model_results = pd.DataFrame({'Model': [model_name], 'RMSE': rmse, 'MAE': mae, 'R2': r2})
    results_df    = pd.concat([results_df, model_results], ignore_index=True)
    return results_df


def run_pipelines_with_metrics_to_dataframe(all_pipelines, X_train, y_train, X_test, y_test):
    results_df = pd.DataFrame(columns=['Model', 'RMSE', 'MAE', 'R2'])

    for model_name, pipeline in all_pipelines.items():
        results_df = train_evaluate_model_with_df(
            model_name, pipeline, 
            X_train, y_train, X_test, y_test, 
            results_df
        )

    results_df = results_df.sort_values(by='R2', ascending=False).reset_index(drop=True)
    return results_df

In [7]:
all_pipelines = create_all_regression_pipelines()
results_df    = run_pipelines_with_metrics_to_dataframe(all_pipelines, X_train, y_train, X_test, y_test)
results_df

                       Model      RMSE       MAE         R2
0                    XGBoost 1.702e+04 1.056e+04  8.153e-01
1               RandomForest 1.714e+04 1.127e+04  8.127e-01
2  HistogramGradientBoosting 2.002e+04 1.456e+04  7.443e-01
3               DecisionTree 2.146e+04 1.024e+04  7.062e-01
4           LinearRegression 2.150e+04 1.212e+04  7.050e-01
5                 KNeighbors 2.834e+04 2.114e+04  4.878e-01
6                        SVR 4.020e+04 3.117e+04 -3.078e-02

> **Observations**:  
>  
> Best-performing models:  
>  
> - **XGBoost** has the lowest RMSE (1.702e+04) and MAE (1.056e+04) with the highest R² (0.8153), making it the top performer.  
> - **Random Forest** follows closely with similar RMSE and MAE but slightly lower R² (0.8127).  
>  
> Moderate performance:  
>  
> - **Histogram Gradient Boosting**, **Decision Tree**, and **Linear Regression** show decent results but with higher errors and lower R² scores (~0.70).  
>  
> Poor performance:  
>  
> - **K-Neighbors** has significantly higher RMSE (2.834e+04) and MAE (2.114e+04), leading to a poor R² (0.4878).  
> - **SVR** performs worst, with extremely high RMSE (4.020e+04) and MAE (3.117e+04), and a negative R² (-0.0378), indicating it fails to explain variance.

> **Conclusion**:  
>  
> - **XGBoost** is the best model, offering the best balance of error minimization and predictive power.  
> - **Random Forest** is a strong alternative, with only a slight drop in performance.  
> - **SVR** and **K-Neighbors** are ineffective for this dataset and should be avoided.

## **4. Test with Best Model**
---

In [8]:
xgb_res        = XGBRegressor()
default_params = xgb_res.get_params()

desired_params          = ['reg_lambda', 'reg_alpha', 'n_estimators', 'max_depth', 'learning_rate', 'gamma', 'colsample_bytree']
selected_default_params = {param: default_params[param] for param in desired_params}

default_params_df = pd.DataFrame([selected_default_params])
default_params_df = default_params_df.transpose()
default_params_df.columns = ['Value']

print('XGBRegressor default params:')
default_params_df.T

XGBRegressor default params:

,reg_lambda,reg_alpha,n_estimators,max_depth,learning_rate,gamma,colsample_bytree
Value,None,None,None,None,None,None,None

In [9]:
categorical_features = X.select_dtypes(include=['object']).columns.tolist()
numerical_features   = X.select_dtypes(include=['int64', 'float64']).columns.tolist()

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_features),
        ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False), categorical_features)
    ]
)

xgb_res = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('regressor', XGBRegressor())
    ]
)

xgb_res.fit(X_train, y_train)
y_pred = xgb_res.predict(X_test)

print(f"RMSE: {root_mean_squared_error(y_test, y_pred):.3f}")
print(f"MAE : {mean_absolute_error(y_test, y_pred):.3f}")
print(f"R2  : {r2_score(y_test, y_pred):.3f}")

RMSE: 17018.299
MAE : 10560.083
R2  : 0.815

## **5. Implementing Optuna for Hyperparameter Tuning**
---

In [10]:
import optuna
from optuna.pruners          import MedianPruner
from sklearn.base            import clone
from sklearn.model_selection import KFold, train_test_split
from sklearn.compose         import ColumnTransformer
from sklearn.preprocessing   import OneHotEncoder, StandardScaler
from xgboost                 import XGBRegressor
from sklearn.metrics         import root_mean_squared_error, mean_absolute_error, r2_score

import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings('ignore')

In [11]:
# Read data
df = pd.read_csv('../data/data_model.csv')
X  = df.drop('Average Salary', axis=1)
y  = df['Average Salary']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Preprocessing
categorical_features = X.select_dtypes(include=['object']).columns.tolist()
numerical_features   = X.select_dtypes(include=['int64', 'float64']).columns.tolist()

preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_features),
        ('cat', OneHotEncoder(handle_unknown='ignore', sparse_output=False), categorical_features),
    ]
)

In [12]:
def objective(trial: optuna.Trial):
    """Define the objective function for Optuna optimization."""

    # Hyperparameter space
    params = {
        'n_estimators'    : trial.suggest_int('n_estimators', 100, 1500, step=50),
        'learning_rate'   : trial.suggest_float('learning_rate', 1e-3, 1, log=True),
        'max_depth'       : trial.suggest_int('max_depth', 3, 21),
        'min_child_weight': trial.suggest_float('min_child_weight', 1, 10),
        'subsample'       : trial.suggest_float('subsample', 0.5, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.5, 1.0),
        'gamma'           : trial.suggest_float('gamma', 0.0, 5.0),
        'reg_alpha'       : trial.suggest_float('reg_alpha', 1e-8, 10.0, log=True),
        'reg_lambda'      : trial.suggest_float('reg_lambda', 1e-8, 10.0, log=True),

        # For faster training
        'tree_method' : 'hist',
        'random_state': 42,
        'n_jobs'      : -1,
    }

    # KFold cross-validation
    kf = KFold(n_splits=5, shuffle=True, random_state=42)
    rmse_scores = []

    # Cross-validation loop and early stopping (each fold will have its own eval_set)
    for fold, (tr_idx, val_idx) in enumerate(kf.split(X_train), start=1):
        X_tr, X_val = X_train.iloc[tr_idx], X_train.iloc[val_idx]
        y_tr, y_val = y_train.iloc[tr_idx], y_train.iloc[val_idx]
        
        prep      = clone(preprocessor)
        X_tr_enc  = prep.fit_transform(X_tr)
        X_val_enc = prep.transform(X_val)

        reg = XGBRegressor(**params, early_stopping_rounds=50)
        reg.fit(
            X_tr_enc, y_tr,
            eval_set = [(X_val_enc, y_val)],
            verbose  = False
        )

        y_pred = reg.predict(X_val_enc)
        rmse   = root_mean_squared_error(y_val, y_pred)
        rmse_scores.append(rmse)

        # Report intermediate results to Optuna and handle pruning
        trial.report(rmse, step=fold)
        if trial.should_prune():
            raise optuna.exceptions.TrialPruned()

    # Object: minimize mean RMSE
    return float(np.mean(rmse_scores))

In [13]:
# Create Optuna study
study = optuna.create_study(
    direction = 'minimize',
    sampler   = optuna.samplers.TPESampler(seed=42),
    pruner    = MedianPruner(n_warmup_steps=5),
)
study.optimize(objective, n_trials=1000, show_progress_bar=True, n_jobs=-1)

[I 2025-08-27 13:09:43,355] A new study created in memory with name: no-name-29d692da-d0c7-41f3-9218-9d3262ae395b

  0%|          | 0/1000 [00:00<?, ?it/s]

[I 2025-08-27 13:09:51,742] Trial 4 finished with value: 20831.948925062545 and parameters: {'n_estimators': 250, 'learning_rate': 0.35774296537689615, 'max_depth': 9, 'min_child_weight': 2.6510557815541125, 'subsample': 0.6392187271053276, 'colsample_bytree': 0.5247291485385017, 'gamma': 4.149450398523152, 'reg_alpha': 5.523729242993812e-06, 'reg_lambda': 8.417578635464899e-08}. Best is trial 4 with value: 20831.948925062545.
[I 2025-08-27 13:09:54,198] Trial 9 finished with value: 21745.42088840127 and parameters: {'n_estimators': 700, 'learning_rate': 0.24272658107229353, 'max_depth': 21, 'min_child_weight': 2.308840271418345, 'subsample': 0.5540474144374554, 'colsample_bytree': 0.8362821508743072, 'gamma': 3.83452661308425, 'reg_alpha': 2.2149553025563018e-05, 'reg_lambda': 0.0019376760139358826}. Best is trial 4 with value: 20831.948925062545.
[I 2025-08-27 13:09:56,032] Trial 7 finished with value: 22042.80661532733 and parameters: {'n_estimators': 550, 'learning_rate': 0.41105513740290645, 'max_depth': 21, 'min_child_weight': 3.508429035303139, 'subsample': 0.6177785993801765, 'colsample_bytree': 0.7391206706399074, 'gamma': 2.487390029397019, 'reg_alpha': 0.0012434223314988471, 'reg_lambda': 4.157326488270658e-06}. Best is trial 4 with value: 20831.948925062545.
[I 2025-08-27 13:09:59,549] Trial 12 finished with value: 23677.5927533008 and parameters: {'n_estimators': 150, 'learning_rate': 0.024378332679014986, 'max_depth': 5, 'min_child_weight': 6.512906482682597, 'subsample': 0.9427163175790385, 'colsample_bytree': 0.9615601464182717, 'gamma': 0.09934846777770956, 'reg_alpha': 1.3937355463892215e-06, 'reg_lambda': 1.9756037014347116}. Best is trial 4 with value: 20831.948925062545.
[I 2025-08-27 13:10:00,655] Trial 13 finished with value: 24422.587070922546 and parameters: {'n_estimators': 650, 'learning_rate': 0.7267545828669267, 'max_depth': 10, 'min_child_weight': 9.208093169174333, 'subsample': 0.635222651128773, 'colsample_bytree': 0.7409873243317717, 'gamma': 1.2354694502146861, 'reg_alpha': 7.423746748585681e-07, 'reg_lambda': 1.3098585671494425}. Best is trial 4 with value: 20831.948925062545.
[I 2025-08-27 13:10:02,662] Trial 6 pruned.
[I 2025-08-27 13:10:02,992] Trial 0 finished with value: 20954.644476904 and parameters: {'n_estimators': 300, 'learning_rate': 0.07544492063603629, 'max_depth': 10, 'min_child_weight': 5.712775490026586, 'subsample': 0.880863968795089, 'colsample_bytree': 0.9597964515726711, 'gamma': 4.610679614334412, 'reg_alpha': 0.07009199072448588, 'reg_lambda': 0.0007644914506981804}. Best is trial 4 with value: 20831.948925062545.
[I 2025-08-27 13:10:04,767] Trial 14 finished with value: 23054.109545863554 and parameters: {'n_estimators': 850, 'learning_rate': 0.6268663737766089, 'max_depth': 14, 'min_child_weight': 9.422200397313594, 'subsample': 0.6844916003172964, 'colsample_bytree': 0.8822247298138804, 'gamma': 3.3687156474128823, 'reg_alpha': 0.0005964281768866348, 'reg_lambda': 8.42914382726831e-05}. Best is trial 4 with value: 20831.948925062545.
[I 2025-08-27 13:10:07,580] Trial 8 pruned.
[I 2025-08-27 13:10:09,730] Trial 17 pruned.
[I 2025-08-27 13:10:16,424] Trial 16 finished with value: 21750.42243206741 and parameters: {'n_estimators': 1400, 'learning_rate': 0.07926955624793383, 'max_depth': 3, 'min_child_weight': 3.9097718525119967, 'subsample': 0.9589474824926254, 'colsample_bytree': 0.6890679391839181, 'gamma': 0.6972666839068625, 'reg_alpha': 0.010181318206081981, 'reg_lambda': 0.18950002211612366}. Best is trial 4 with value: 20831.948925062545.
[I 2025-08-27 13:10:17,563] Trial 18 pruned.
[I 2025-08-27 13:10:22,079] Trial 2 pruned.
[I 2025-08-27 13:10:22,464] Trial 20 finished with value: 20326.80913613411 and parameters: {'n_estimators': 1500, 'learning_rate': 0.1492816660572148, 'max_depth': 15, 'min_child_weight': 2.873253053945157, 'subsample': 0.8792911603413349, 'colsample_bytree': 0.7426852535279359, 'gamma': 0.6334880143908878, 'reg_alpha': 3.877346153034128e-07, 'reg_lambda': 2.5819893440659957e-05}. Best is trial 20 with value: 20326.80913613411.
[I 2025-08-27 13:10:24,094] Trial 11 pruned.
[I 2025-08-27 13:10:32,766] Trial 21 finished with value: 20553.781046713302 and parameters: {'n_estimators': 1250, 'learning_rate': 0.08999578787153005, 'max_depth': 16, 'min_child_weight': 4.032716112650905, 'subsample': 0.7898455276511459, 'colsample_bytree': 0.6475550367431299, 'gamma': 4.807548786654135, 'reg_alpha': 3.455224348604651e-08, 'reg_lambda': 0.01618471867955029}. Best is trial 20 with value: 20326.80913613411.
[I 2025-08-27 13:10:37,384] Trial 23 finished with value: 20695.20662187125 and parameters: {'n_estimators': 350, 'learning_rate': 0.1139725867639439, 'max_depth': 14, 'min_child_weight': 4.933066056176939, 'subsample': 0.8325186624549931, 'colsample_bytree': 0.635806182413526, 'gamma': 4.9532248706724955, 'reg_alpha': 1.3928212150383887, 'reg_lambda': 0.001574527521923614}. Best is trial 20 with value: 20326.80913613411.
[I 2025-08-27 13:10:38,349] Trial 26 finished with value: 20771.63117119249 and parameters: {'n_estimators': 1000, 'learning_rate': 0.1613180553721881, 'max_depth': 15, 'min_child_weight': 1.157965455893156, 'subsample': 0.7911200414150983, 'colsample_bytree': 0.639887755457614, 'gamma': 4.829369466497468, 'reg_alpha': 1.0704884175511713e-08, 'reg_lambda': 1.570937752939588e-05}. Best is trial 20 with value: 20326.80913613411.
[I 2025-08-27 13:10:39,497] Trial 22 finished with value: 20815.66017965004 and parameters: {'n_estimators': 300, 'learning_rate': 0.1202492787071821, 'max_depth': 15, 'min_child_weight': 5.681919902897002, 'subsample': 0.8289846768427338, 'colsample_bytree': 0.6446839378299696, 'gamma': 4.919369602759008, 'reg_alpha': 3.427230664914772e-08, 'reg_lambda': 0.0019041938441362203}. Best is trial 20 with value: 20326.80913613411.
[I 2025-08-27 13:10:41,441] Trial 10 finished with value: 21197.524184902202 and parameters: {'n_estimators': 500, 'learning_rate': 0.011799121866453509, 'max_depth': 18, 'min_child_weight': 4.9709576788126135, 'subsample': 0.6196100540531254, 'colsample_bytree': 0.8521041461909701, 'gamma': 2.676873239583003, 'reg_alpha': 0.0012546272961458382, 'reg_lambda': 8.697585863588281e-07}. Best is trial 20 with value: 20326.80913613411.
[I 2025-08-27 13:10:44,309] Trial 24 finished with value: 20673.13256461353 and parameters: {'n_estimators': 350, 'learning_rate': 0.10244638427131121, 'max_depth': 14, 'min_child_weight': 4.312319501638965, 'subsample': 0.8358908471465292, 'colsample_bytree': 0.6406499710591343, 'gamma': 4.984102038259335, 'reg_alpha': 2.7920017306318818e-08, 'reg_lambda': 3.948069786247753e-05}. Best is trial 20 with value: 20326.80913613411.
[I 2025-08-27 13:10:54,151] Trial 27 finished with value: 20752.05417609699 and parameters: {'n_estimators': 1500, 'learning_rate': 0.10649933779321463, 'max_depth': 16, 'min_child_weight': 4.481246913528753, 'subsample': 0.8057533472848168, 'colsample_bytree': 0.6342578815797139, 'gamma': 4.991214050503192, 'reg_alpha': 1.088742319920176e-08, 'reg_lambda': 0.029093299600782527}. Best is trial 20 with value: 20326.80913613411.
[I 2025-08-27 13:10:56,432] Trial 5 pruned.
[I 2025-08-27 13:10:59,036] Trial 28 finished with value: 20877.391920779668 and parameters: {'n_estimators': 1500, 'learning_rate': 0.1522384651258013, 'max_depth': 17, 'min_child_weight': 4.282217743885576, 'subsample': 0.7845014483760706, 'colsample_bytree': 0.6399923096608475, 'gamma': 1.969891720516204, 'reg_alpha': 3.224355703553087e-08, 'reg_lambda': 0.033518155772258834}. Best is trial 20 with value: 20326.80913613411.
[I 2025-08-27 13:11:00,183] Trial 19 pruned.
[I 2025-08-27 13:11:05,356] Trial 31 finished with value: 20461.093669196835 and parameters: {'n_estimators': 1500, 'learning_rate': 0.06322294439845398, 'max_depth': 19, 'min_child_weight': 3.565365600958372, 'subsample': 0.9062591185777474, 'colsample_bytree': 0.7677047701368274, 'gamma': 2.1209871818713353, 'reg_alpha': 1.0628302833411189e-07, 'reg_lambda': 0.03755257695785179}. Best is trial 20 with value: 20326.80913613411.
[I 2025-08-27 13:11:07,675] Trial 29 finished with value: 20955.430750054984 and parameters: {'n_estimators': 1500, 'learning_rate': 0.05441360950135165, 'max_depth': 18, 'min_child_weight': 4.218341524232531, 'subsample': 0.8832643866849186, 'colsample_bytree': 0.802858052393528, 'gamma': 1.7981573559669304, 'reg_alpha': 1.3714094254317639e-08, 'reg_lambda': 0.048762451171214104}. Best is trial 20 with value: 20326.80913613411.
[I 2025-08-27 13:11:15,070] Trial 32 finished with value: 20327.608560585773 and parameters: {'n_estimators': 1500, 'learning_rate': 0.052410125286751125, 'max_depth': 17, 'min_child_weight': 3.7375308593211707, 'subsample': 0.8932837036651777, 'colsample_bytree': 0.7887234143136082, 'gamma': 1.8344367116033973, 'reg_alpha': 1.4466575159387995e-07, 'reg_lambda': 0.01580454702163138}. Best is trial 20 with value: 20326.80913613411.
[I 2025-08-27 13:11:21,806] Trial 30 finished with value: 20653.409392710055 and parameters: {'n_estimators': 1500, 'learning_rate': 0.05359764014647333, 'max_depth': 18, 'min_child_weight': 4.295956883895818, 'subsample': 0.75026565025236, 'colsample_bytree': 0.7988621579111157, 'gamma': 2.313031297561752, 'reg_alpha': 1.232330629140248e-07, 'reg_lambda': 0.03306837480920426}. Best is trial 20 with value: 20326.80913613411.
[I 2025-08-27 13:11:26,032] Trial 36 finished with value: 20463.3567437855 and parameters: {'n_estimators': 1250, 'learning_rate': 0.05349976295990654, 'max_depth': 12, 'min_child_weight': 3.2827793641881904, 'subsample': 0.9021436339861323, 'colsample_bytree': 0.7897640261754115, 'gamma': 4.2354392769657245, 'reg_alpha': 3.022563303967962e-07, 'reg_lambda': 7.969857496109124e-05}. Best is trial 20 with value: 20326.80913613411.
[I 2025-08-27 13:11:26,090] Trial 34 finished with value: 20618.907772532235 and parameters: {'n_estimators': 1250, 'learning_rate': 0.049570123240663726, 'max_depth': 18, 'min_child_weight': 3.198777124363387, 'subsample': 0.9063953175639212, 'colsample_bytree': 0.7861266552303473, 'gamma': 4.377464655058354, 'reg_alpha': 9.57456828646377e-08, 'reg_lambda': 0.00010503254381102551}. Best is trial 20 with value: 20326.80913613411.
[I 2025-08-27 13:11:32,490] Trial 33 finished with value: 20429.725229744534 and parameters: {'n_estimators': 1250, 'learning_rate': 0.04964961342569466, 'max_depth': 18, 'min_child_weight': 3.35240505229001, 'subsample': 0.8933454118698255, 'colsample_bytree': 0.7882576589014998, 'gamma': 1.8794711177239374, 'reg_alpha': 1.4411589058037278e-07, 'reg_lambda': 0.00010091544081733109}. Best is trial 20 with value: 20326.80913613411.
[I 2025-08-27 13:11:34,073] Trial 35 finished with value: 20329.34696745543 and parameters: {'n_estimators': 1200, 'learning_rate': 0.05215865512878319, 'max_depth': 19, 'min_child_weight': 3.003058508099649, 'subsample': 0.8918351617713418, 'colsample_bytree': 0.6999327028508107, 'gamma': 4.427925212878904, 'reg_alpha': 1.94290086019211e-07, 'reg_lambda': 0.00012577226641352393}. Best is trial 20 with value: 20326.80913613411.
[I 2025-08-27 13:11:39,085] Trial 37 finished with value: 20212.16649113554 and parameters: {'n_estimators': 1200, 'learning_rate': 0.04381552712291393, 'max_depth': 19, 'min_child_weight': 3.157300977455903, 'subsample': 0.8974397496189648, 'colsample_bytree': 0.7866185742689144, 'gamma': 1.8645513094006365, 'reg_alpha': 2.0309515700996632e-07, 'reg_lambda': 0.021619779448764063}. Best is trial 37 with value: 20212.16649113554.
[I 2025-08-27 13:11:41,990] Trial 1 pruned.
[I 2025-08-27 13:11:44,184] Trial 43 pruned.
[I 2025-08-27 13:11:44,557] Trial 3 pruned.
[I 2025-08-27 13:11:46,307] Trial 38 pruned.
[I 2025-08-27 13:11:49,647] Trial 15 pruned.
[I 2025-08-27 13:11:50,756] Trial 39 finished with value: 20442.562884837993 and parameters: {'n_estimators': 1250, 'learning_rate': 0.043504019116670595, 'max_depth': 12, 'min_child_weight': 3.019024938739289, 'subsample': 0.9121650681549979, 'colsample_bytree': 0.7831365243618762, 'gamma': 1.5245240904480624, 'reg_alpha': 1.821819974340078e-07, 'reg_lambda': 0.00019686187438347974}. Best is trial 37 with value: 20212.16649113554.
[I 2025-08-27 13:11:53,528] Trial 42 pruned.
[I 2025-08-27 13:11:59,114] Trial 45 pruned.
[I 2025-08-27 13:11:59,379] Trial 41 pruned.
[I 2025-08-27 13:12:02,809] Trial 44 pruned.
[I 2025-08-27 13:12:03,463] Trial 40 pruned.
[I 2025-08-27 13:12:12,471] Trial 55 pruned.
[I 2025-08-27 13:12:18,237] Trial 46 pruned.
[I 2025-08-27 13:12:27,426] Trial 48 finished with value: 20327.336743615073 and parameters: {'n_estimators': 1100, 'learning_rate': 0.03482509307784963, 'max_depth': 20, 'min_child_weight': 2.6435814621610776, 'subsample': 0.8453116439637942, 'colsample_bytree': 0.718801440012004, 'gamma': 1.5528216538248998, 'reg_alpha': 2.053946988068597e-06, 'reg_lambda': 0.005913562542263566}. Best is trial 37 with value: 20212.16649113554.
[I 2025-08-27 13:12:40,826] Trial 47 pruned.
[I 2025-08-27 13:12:47,937] Trial 51 pruned.
[I 2025-08-27 13:12:48,898] Trial 49 finished with value: 20437.694255922346 and parameters: {'n_estimators': 1150, 'learning_rate': 0.016166918859863755, 'max_depth': 16, 'min_child_weight': 2.7074639513487813, 'subsample': 0.8560804838578777, 'colsample_bytree': 0.701384723575465, 'gamma': 1.5569029708370028, 'reg_alpha': 3.675328026099938e-06, 'reg_lambda': 0.006399184599152653}. Best is trial 37 with value: 20212.16649113554.
[I 2025-08-27 13:12:55,476] Trial 52 finished with value: 20552.553260238805 and parameters: {'n_estimators': 1100, 'learning_rate': 0.015653060977027834, 'max_depth': 17, 'min_child_weight': 2.238888079777724, 'subsample': 0.8654161110185384, 'colsample_bytree': 0.8269916069706893, 'gamma': 0.8206069052403544, 'reg_alpha': 1.798902648791921e-06, 'reg_lambda': 0.0005230264152799266}. Best is trial 37 with value: 20212.16649113554.
[I 2025-08-27 13:13:14,487] Trial 54 finished with value: 20581.7824593037 and parameters: {'n_estimators': 1100, 'learning_rate': 0.01662001648626875, 'max_depth': 17, 'min_child_weight': 2.430817204684203, 'subsample': 0.8605191664787436, 'colsample_bytree': 0.8176157293262114, 'gamma': 0.9277780509752325, 'reg_alpha': 2.589800469457224e-06, 'reg_lambda': 1.6184137926957446e-05}. Best is trial 37 with value: 20212.16649113554.
[I 2025-08-27 13:13:16,267] Trial 50 pruned.
[I 2025-08-27 13:13:25,859] Trial 57 finished with value: 20397.87014092088 and parameters: {'n_estimators': 1400, 'learning_rate': 0.01617705447767626, 'max_depth': 17, 'min_child_weight': 2.443362467331229, 'subsample': 0.8641483897110962, 'colsample_bytree': 0.6768227186705074, 'gamma': 2.718843863327368, 'reg_alpha': 9.611032718247621e-06, 'reg_lambda': 0.007898332400581432}. Best is trial 37 with value: 20212.16649113554.
[I 2025-08-27 13:13:25,971] Trial 53 finished with value: 20629.58175805088 and parameters: {'n_estimators': 1100, 'learning_rate': 0.01685908066701018, 'max_depth': 17, 'min_child_weight': 3.0196779730970946, 'subsample': 0.8601623235261731, 'colsample_bytree': 0.826578678134427, 'gamma': 0.9967531908601784, 'reg_alpha': 2.2312045761126452e-06, 'reg_lambda': 1.9334069733094487e-05}. Best is trial 37 with value: 20212.16649113554.
[I 2025-08-27 13:13:28,929] Trial 63 finished with value: 20422.18535419501 and parameters: {'n_estimators': 1400, 'learning_rate': 0.0688195405681274, 'max_depth': 21, 'min_child_weight': 3.6924903563271716, 'subsample': 0.9655506257736136, 'colsample_bytree': 0.6779954917304957, 'gamma': 2.513972921376994, 'reg_alpha': 6.023561587778241e-07, 'reg_lambda': 0.16426939596069}. Best is trial 37 with value: 20212.16649113554.
[I 2025-08-27 13:13:32,642] Trial 25 pruned.
[I 2025-08-27 13:13:51,049] Trial 56 finished with value: 20663.660776220855 and parameters: {'n_estimators': 1350, 'learning_rate': 0.0092285551773842, 'max_depth': 17, 'min_child_weight': 2.421605744317329, 'subsample': 0.8598827316119063, 'colsample_bytree': 0.8289638368776066, 'gamma': 0.9662472181100679, 'reg_alpha': 2.1886328449983654e-06, 'reg_lambda': 1.5228466637960264e-05}. Best is trial 37 with value: 20212.16649113554.
[I 2025-08-27 13:13:53,371] Trial 59 finished with value: 20423.04878454771 and parameters: {'n_estimators': 1400, 'learning_rate': 0.014331332061240635, 'max_depth': 17, 'min_child_weight': 2.7114678406786057, 'subsample': 0.8624553407835437, 'colsample_bytree': 0.6800011330497455, 'gamma': 0.9790556322019983, 'reg_alpha': 8.058856153675622e-06, 'reg_lambda': 0.12011237478637844}. Best is trial 37 with value: 20212.16649113554.
[I 2025-08-27 13:13:59,907] Trial 58 finished with value: 20505.111601823428 and parameters: {'n_estimators': 1400, 'learning_rate': 0.013608030699917877, 'max_depth': 17, 'min_child_weight': 3.7081009392678235, 'subsample': 0.8618841059558118, 'colsample_bytree': 0.673573556292662, 'gamma': 2.6647787168513903, 'reg_alpha': 6.319634552615102e-06, 'reg_lambda': 0.005775950281798376}. Best is trial 37 with value: 20212.16649113554.
[I 2025-08-27 13:14:09,354] Trial 61 finished with value: 20470.46262207851 and parameters: {'n_estimators': 1400, 'learning_rate': 0.0164477250917454, 'max_depth': 17, 'min_child_weight': 3.777028422393152, 'subsample': 0.7270182274278598, 'colsample_bytree': 0.6726023510010812, 'gamma': 2.6274648411927197, 'reg_alpha': 8.709299434779554e-07, 'reg_lambda': 0.0010535600102566983}. Best is trial 37 with value: 20212.16649113554.
[I 2025-08-27 13:14:19,382] Trial 60 finished with value: 20328.68535108501 and parameters: {'n_estimators': 1350, 'learning_rate': 0.014435957736264224, 'max_depth': 17, 'min_child_weight': 3.6076145367792836, 'subsample': 0.9439743081797297, 'colsample_bytree': 0.6714991068877625, 'gamma': 0.9498954106471713, 'reg_alpha': 8.654714831073885e-06, 'reg_lambda': 0.00804534269998565}. Best is trial 37 with value: 20212.16649113554.
[I 2025-08-27 13:14:48,481] Trial 73 pruned.
[I 2025-08-27 13:14:55,522] Trial 70 pruned.
[I 2025-08-27 13:15:01,430] Trial 62 finished with value: 20638.4737419984 and parameters: {'n_estimators': 1400, 'learning_rate': 0.008892275895611654, 'max_depth': 17, 'min_child_weight': 3.7778868874483145, 'subsample': 0.9534680299082079, 'colsample_bytree': 0.816521855277563, 'gamma': 2.4933734041567677, 'reg_alpha': 8.360055328266132e-07, 'reg_lambda': 0.08112785650831161}. Best is trial 37 with value: 20212.16649113554.
[I 2025-08-27 13:15:08,157] Trial 72 finished with value: 20593.842254198014 and parameters: {'n_estimators': 1450, 'learning_rate': 0.02841337372883927, 'max_depth': 21, 'min_child_weight': 4.688846383574124, 'subsample': 0.9470997084790719, 'colsample_bytree': 0.601290150129364, 'gamma': 2.2791921159051567, 'reg_alpha': 9.07902646481867e-07, 'reg_lambda': 0.2716226616688404}. Best is trial 37 with value: 20212.16649113554.
[I 2025-08-27 13:15:10,981] Trial 71 pruned.
[I 2025-08-27 13:15:18,536] Trial 79 pruned.
[I 2025-08-27 13:15:22,988] Trial 64 finished with value: 20484.98683479015 and parameters: {'n_estimators': 1400, 'learning_rate': 0.010898821159098954, 'max_depth': 21, 'min_child_weight': 3.6021326317192317, 'subsample': 0.9592516426285721, 'colsample_bytree': 0.7395975790449122, 'gamma': 2.438602655332634, 'reg_alpha': 8.76350509326933e-07, 'reg_lambda': 0.1773421700267935}. Best is trial 37 with value: 20212.16649113554.
[I 2025-08-27 13:15:38,620] Trial 68 finished with value: 20731.290060215753 and parameters: {'n_estimators': 1400, 'learning_rate': 0.00956012598471745, 'max_depth': 19, 'min_child_weight': 4.64499672665196, 'subsample': 0.9316488223345818, 'colsample_bytree': 0.743414581942255, 'gamma': 0.006455235848836893, 'reg_alpha': 8.877627980256796e-06, 'reg_lambda': 0.13788556416501377}. Best is trial 37 with value: 20212.16649113554.
[I 2025-08-27 13:15:46,971] Trial 65 pruned.

In [14]:
# Report the best trial
print('Best trial :', study.best_trial.number)
print('Best RMSE  :', study.best_value)
print('Best params:')
for k, v in study.best_params.items():
    print(f"\t{k}: {v}")

Best trial : 775
Best RMSE  : 19048.01270075514
Best params:
	n_estimators: 1000
	learning_rate: 0.2259819565429738
	max_depth: 11
	min_child_weight: 1.477327898415538
	subsample: 0.8990850732677914
	colsample_bytree: 0.5103249628264016
	gamma: 2.792911522391636
	reg_alpha: 2.501904739969501e-07
	reg_lambda: 0.18999603922081723

In [15]:
# Re-train the model with the best hyperparameters
X_tr, X_val, y_tr, y_val = train_test_split(X_train, y_train, test_size=0.15, random_state=42)

prep      = clone(preprocessor)
X_tr_enc  = prep.fit_transform(X_tr)
X_val_enc = prep.transform(X_val)

best_reg = XGBRegressor(
    **study.best_params,
    tree_method           = 'hist',
    random_state          = 42,
    n_jobs                = -1,
    early_stopping_rounds = 50,
)

best_reg.fit(
    X_tr_enc, y_tr,
    eval_set = [(X_val_enc, y_val)],
    verbose  = False,
)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.5103249628264016, device=None,
             early_stopping_rounds=50, enable_categorical=False,
             eval_metric=None, feature_types=None, feature_weights=None,
             gamma=2.792911522391636, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.2259819565429738,
             max_bin=None, max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=11, max_leaves=None,
             min_child_weight=1.477327898415538, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=1000,
             n_jobs=-1, num_parallel_tree=None, ...)

## **6. Evaluation**
---

In [22]:
from sklearn.pipeline import Pipeline
best_model = Pipeline([
    ('preprocessor', prep),
    ('regressor'   , best_reg),
])

y_pred = best_model.predict(X_test)

print(f"RMSE: {root_mean_squared_error(y_test, y_pred):.3f}")
print(f"MAE : {mean_absolute_error(y_test, y_pred):.3f}")
print(f"R2  : {r2_score(y_test, y_pred):.3f}")

RMSE: 17954.026
MAE : 9503.655
R2  : 0.794

## **7. Save Model**
---

In [23]:
import os
import joblib

OUTPUT_DIR  = '../outputs/optuna_xgboost'
os.makedirs(OUTPUT_DIR, exist_ok=True)

joblib.dump(best_model, f"{OUTPUT_DIR}/xgb_optuna_tuning.pkl")
print(f'XGBoost model with Optuna tuning saved to {OUTPUT_DIR}/xgb_optuna_tuning.pkl')

XGBoost model with Optuna tuning saved to ../outputs/optuna_xgboost/xgb_optuna_tuning.pkl